## Basic Configuration

baseurl = "https://robotomize.me"
builddrafts = true
canonifyurls = false
languageCode = "en-US"
showcomments = false
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Ivanov Nikita"
title = "Software engineer"

theme = "researcher"

## Hugo Built-in Features
disqusShortname = "" # Comment out to disable Disqus.
googleAnalytics = ""
enableRobotsTXT = true

## Site Settings
[params]
author = "Ivanov Nikita"
intro = "software engineer"
description = "I build projects, sometimes they work:)"
authorimage = "headshot.jpg"
dateformat = "Jan 2, 2006"
mainSections = ["about"]
## Site Meta Settings
[params.meta]
description = "Software engineer 🧑💻"
keywords = "Go, golang, PHP, JavaScript, TypeScript"

## Social Accounts
[params.social]
github = "robotomize"
medium = "@robotomize"
instagram = "robotomize"
linkedin = "ivanovnikita"
telegram = "robotomize"
email = "robotomize@gmail.com"

[params.footer]
text = "@2021 Ivanov Nikita"
url = "https://robotomize.me"

[params.style]  # appearance options (can be omitted)
fontFamily = "Inconsolata"
pageWidth = "750px"
avatarSize = "90px"
colorBlack = "#222222"
colorRed = "#dc3545"
[[params.socialIcons]]
icon = "fab fa-twitter"
title = "Twitter"
url = "https://twitter.com/robotomize"
[[params.socialIcons]]
icon = "fas fa-envelope"
title = "E-mail"
url = "mailto:robotomize@gmail.com"

## Extras
[params.extra]
copyright = "©2020. Ivanov Nikita"
poweredby = false
highlightjs = true
socialmarkup = true
toc = true
displayrssicon = false

[permalinks]
"/" = "/:filename"

[menu]
[[menu.main]]
name = "About"
url = "/about"
weight = 1


[markup.goldmark.renderer]
unsafe = true